/**
 * @file fdcan_bus.c
 * @author Zhengbi Yong (zhengbi.yong@outlook.com)
 * @brief  CAN bus management module implementation.
 * @version 0.1
 * @date 2025-11-18
 *
 * @note   This file defines global CAN bus objects for FDCAN1 and FDCAN2.
 *         These objects are initialized with default values and bound to
 *         their respective FDCAN handles.
 *
 * Zhengbi Yong
 *
 */
#include "fdcan_bus.h"

/* External FDCAN handle declarations (defined in main.c or generated by CubeMX) */
extern FDCAN_HandleTypeDef hfdcan1;
extern FDCAN_HandleTypeDef hfdcan2;

/**
 * @brief  Global CAN bus object for FDCAN1.
 *
 * @note   This object is initialized with:
 *         - hfdcan: bound to &hfdcan1
 *         - motor_count: 15 (can be adjusted based on actual motor count)
 *         - start_flag: 0 (not started, will be set to 1 after initialization)
 *
 * @note   The motor array is automatically zero-initialized by the compiler.
 *         Individual motors should be initialized using joint_motor_init()
 *         before use.
 */
fdcan_bus_t fdcan1_bus = {
    .hfdcan = &hfdcan1,      /* Bind to FDCAN1 handle */
    .motor_count = 15,        /* Default motor count (adjust as needed) */
    .start_flag = 0,          /* Not started initially */
    /* motor array is zero-initialized automatically */
};

/**
 * @brief  Global CAN bus object for FDCAN2.
 *
 * @note   This object is initialized with:
 *         - hfdcan: bound to &hfdcan2
 *         - motor_count: 15 (can be adjusted based on actual motor count)
 *         - start_flag: 0 (not started, will be set to 1 after initialization)
 *
 * @note   The motor array is automatically zero-initialized by the compiler.
 *         Individual motors should be initialized using joint_motor_init()
 *         before use.
 */
fdcan_bus_t fdcan2_bus = {
    .hfdcan = &hfdcan2,      /* Bind to FDCAN2 handle */
    .motor_count = 15,        /* Default motor count (adjust as needed) */
    .start_flag = 0,          /* Not started initially */
    /* motor array is zero-initialized automatically */
};
